### ISSUE TITLE
Add a database query to the city filters

### ISSUE THREAD

**Issue by Musilah** [mainflux/callhome#23]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Implementing the city filter on the front end but the filter is not picking up any data from the data base. Add queries to timescale.go. 
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
must have

**Comment by SammyOina** [comment]
city filters seems to work just fine, make sure your fork is in sync
![image](https://github.com/mainflux/callhome/assets/44265300/e3c63015-03be-42a3-aa7e-88538257fcb2)

**Comment by Musilah** [comment]
It was the query issue and I have resolved it.
